const constants = {
    API_URL: `/api`,
    //API_URL: `http://localhost:3001/api`,

    GET_RELAYS: "GET_RELAYS",
    CURRENT_RELAY: "CURRENT_RELAY",
    RELAYS_SUCCESS: "RELAYS_SUCCESS",
    RELAYS_FAILURE: "RELAYS_FAILURE",

    AUTHORIZATION_USER: "AUTHORIZATION_USER",
    AUTH_FAILURE: "AUTH_FAILURE",
    AUTH_SUCCESS: "AUTH_SUCCESS",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT: "LOGOUT",

    REGISTER_USER: "REGISTER_USER",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",

    CHANGE_USER: "CHANGE_USER",
    CHANGE_SUCCESS: "CHANGE_SUCCESS",
    CHANGE_FAILURE: "CHANGE_FAILURE",

    REMOVE_USER: "REMOVE_USER",
    REMOVE_SUCCESS: "REMOVE_SUCCESS",
    REMOVE_FAILURE: "REMOVE_FAILURE",

    OFFER_RELAY: "OFFER_RELAY",
    OFFER_SUCCESS: "OFFER_SUCCESS",
    OFFER_FAILURE: "OFFER_FAILURE",

    TOGGLE_CLASS: "TOGGLE_CLASS",
    ROUTE_UPDATE: "ROUTE_UPDATE"
}

export default constants
